[project]
name = "fc-analytics"
version = "0.1.0"
description = "Fine Cooking Analytics"
readme = "README.md"
authors = [
    { name = "John Ludlum", email = "john.ludlum2@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "pymupdf>=1.28.0",
    "pytesseract>=0.3.13",
    "pyyaml>=6.0.3",
    "streamlit>=1.61.0",
]

[project.scripts]
fc-analytics = "fc_analytics:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
